[package]
name = "mongo_drop"
version = "0.2.0"
edition = "2024"
authors = ["Shaun Hamilton <shauhami020@gmail.com>"]
description = "An RAII to rollback MongoDB transactions on drop"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ShaunSHamilton/mongo_drop/"
categories = ["asynchronous", "database", "development-tools::testing"]
keywords = ["mongodb", "drop", "rollback", "transaction"]

[dependencies]
futures-util = "0.3.31"
mongodb = "3.3.0"
tokio = { version = "1.48.0", features = ["full"] }
tracing = { version = "0.1.41", optional = true }

[features]
tracing = ["dep:tracing"]

[dev-dependencies]
test-log = { version = "0.2.18", features = ["trace"] }
